#!/usr/bin/env node

/**
 * JSON → CSS 토큰 동기화 스크립트 (fai-homepage 경량 버전)
 *
 * `node scripts/sync-tokens.js` 실행 시 root/foundation/*.json 을 읽어
 * CSS 변수를 자동 생성합니다.
 *
 * 처리 파일:
 *   - color-global.json
 *   - color-semantic.json
 *   - typography.json
 *   - spacing.json
 */

const fs = require('fs');
const path = require('path');

const ROOT       = path.resolve(__dirname, '..');
const FOUNDATION = path.join(ROOT, 'root', 'foundation');

const HEADER = '/* Generated by scripts/sync-tokens.js — DO NOT EDIT DIRECTLY */\n';

// ─── 유틸 ────────────────────────────────────

function resolveRefs(value) {
  if (typeof value !== 'string') return String(value);
  return value.replace(/\{([^}]+)\}/g, (_, p) => `var(--${p.replace(/\./g, '-')})`);
}

function flattenToVars(obj, prefix = '') {
  const vars = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key === '$meta') continue;
    const varName = key === '_' ? prefix : (prefix ? `${prefix}-${key}` : key);
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      Object.assign(vars, flattenToVars(value, varName));
    } else {
      vars[`--${varName}`] = resolveRefs(value);
    }
  }
  return vars;
}

function renderVars(vars, indent = '  ') {
  return Object.entries(vars)
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join('\n');
}

function filterByPrefix(vars, prefix) {
  return Object.fromEntries(
    Object.entries(vars).filter(([k]) => k.startsWith(`--${prefix}-`) || k === `--${prefix}`)
  );
}

function readJSON(filename) {
  return JSON.parse(fs.readFileSync(path.join(FOUNDATION, filename), 'utf-8'));
}

function writeFile(dir, filename, content) {
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, filename), content, 'utf-8');
  const rel = path.relative(ROOT, path.join(dir, filename));
  console.log(`  ✓ ${rel}`);
}

// ─── foundation/ 공유 토큰 CSS ───────────────

function generateColorCSS() {
  const global   = readJSON('color-global.json');
  const semantic = readJSON('color-semantic.json');

  const globalVars = flattenToVars(global, 'color');
  const lightVars  = flattenToVars(semantic.light, 'color');

  const content = [
    HEADER,
    '@theme {',
    '  /* Global Colors */',
    renderVars(globalVars),
    '',
    '  /* Semantic Colors (Light) */',
    renderVars(lightVars),
    '}',
    '',
  ].join('\n');

  writeFile(FOUNDATION, 'color.css', content);
}

function generateDarkCSS() {
  const darkVars = flattenToVars(readJSON('color-semantic.json').dark, 'color');
  writeFile(FOUNDATION, 'dark.css',
    HEADER + `:where(.dark) {\n${renderVars(darkVars)}\n}\n`);
}

function generateTypographyCSS() {
  const vars = flattenToVars(readJSON('typography.json'), 'font');
  const sections = [
    ['/* Font Family */',    filterByPrefix(vars, 'font-family')],
    ['/* Font Weight */',    filterByPrefix(vars, 'font-weight')],
    ['/* Font Size */',      filterByPrefix(vars, 'font-size')],
    ['/* Line Height */',    filterByPrefix(vars, 'font-lineHeight')],
    ['/* Letter Spacing */', filterByPrefix(vars, 'font-letterSpacing')],
  ].filter(([, v]) => Object.keys(v).length > 0);

  const body = sections.map(([c, v]) => `  ${c}\n${renderVars(v)}`).join('\n\n');
  writeFile(FOUNDATION, 'typography.css', HEADER + `@theme {\n${body}\n}\n`);
}

function generateSpacingCSS() {
  const spacing = readJSON('spacing.json');
  const vars = flattenToVars(spacing);
  const sections = [
    ['/* Spacing */',        filterByPrefix(vars, 'spacing')],
    ['/* Border Radius */',  filterByPrefix(vars, 'borderRadius')],
  ].filter(([, v]) => Object.keys(v).length > 0);

  const body = sections.map(([c, v]) => `  ${c}\n${renderVars(v)}`).join('\n\n');
  writeFile(FOUNDATION, 'spacing.css', HEADER + `@theme {\n${body}\n}\n`);
}

// ─── 실행 ─────────────────────────────────────
console.log('\n🔄 토큰 동기화 시작...\n');
try {
  console.log('[ foundation/ — 공유 토큰 ]');
  generateColorCSS();
  generateDarkCSS();
  generateTypographyCSS();
  generateSpacingCSS();

  console.log('\n✅ 동기화 완료\n');
} catch (err) {
  console.error('\n❌ 동기화 실패:', err.message);
  console.error(err.stack);
  process.exit(1);
}
