#!/usr/bin/env node

/**
 * JSON → CSS 토큰 동기화 스크립트
 *
 * `npm run sync` 실행 시 root/foundation/*.json 을 읽어
 * 플랫폼별 CSS를 자동 생성합니다.
 *
 * 출력 구조:
 *   root/foundation/  ← 공유 토큰 CSS (color, opacity, effects, font 원시값)
 *   root/web/         ← 웹 플랫폼 CSS (mw spacing + web typography)
 *   root/vg/          ← VGK 플랫폼 CSS (vgk spacing + tablet typography)
 *
 * 참조 표기법: {path.to.token} → var(--path-to-token)
 */

const fs = require('fs');
const path = require('path');

const ROOT        = path.resolve(__dirname, '..');
const FOUNDATION  = path.join(ROOT, 'root', 'foundation');
const WEB_OUT     = path.join(ROOT, 'root', 'web');
const VG_OUT      = path.join(ROOT, 'root', 'vg');

const HEADER = '/* Generated by scripts/sync-tokens.js — DO NOT EDIT DIRECTLY */\n';

// ─── 유틸 ────────────────────────────────────

function resolveRefs(value) {
  if (typeof value !== 'string') return String(value);
  return value.replace(/\{([^}]+)\}/g, (_, p) => `var(--${p.replace(/\./g, '-')})`);
}

function flattenToVars(obj, prefix = '') {
  const vars = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key === '$meta') continue;
    const varName = key === '_' ? prefix : (prefix ? `${prefix}-${key}` : key);
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      Object.assign(vars, flattenToVars(value, varName));
    } else {
      vars[`--${varName}`] = resolveRefs(value);
    }
  }
  return vars;
}

function renderVars(vars, indent = '  ') {
  return Object.entries(vars)
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join('\n');
}

function diffVars(base, override) {
  return Object.fromEntries(
    Object.entries(override).filter(([k, v]) => base[k] !== v)
  );
}

function filterByPrefix(vars, prefix) {
  return Object.fromEntries(
    Object.entries(vars).filter(([k]) => k.startsWith(`--${prefix}-`) || k === `--${prefix}`)
  );
}

function readJSON(filename) {
  return JSON.parse(fs.readFileSync(path.join(FOUNDATION, filename), 'utf-8'));
}

function writeFile(dir, filename, content) {
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, filename), content, 'utf-8');
  const rel = path.relative(ROOT, path.join(dir, filename));
  console.log(`  ✓ ${rel}`);
}

function themeBlock(vars) {
  return `@theme {\n${renderVars(vars)}\n}`;
}

// ─── foundation/ 공유 토큰 CSS ───────────────

function generateColorCSS() {
  const global   = readJSON('color-global.json');
  const semantic = readJSON('color-semantic.json');

  const globalVars = flattenToVars(global, 'color');
  const lightVars  = flattenToVars(semantic.light, 'color');

  const content = [
    HEADER,
    '@theme {',
    '  /* Global Colors */',
    renderVars(globalVars),
    '',
    '  /* Semantic Colors (Light) */',
    renderVars(lightVars),
    '}',
    '',
  ].join('\n');

  writeFile(FOUNDATION, 'color.css', content);
}

function generateDarkCSS() {
  const darkVars = flattenToVars(readJSON('color-semantic.json').dark, 'color');
  writeFile(FOUNDATION, 'dark.css',
    HEADER + `:where(.dark) {\n${renderVars(darkVars)}\n}\n`);
}

function generateColorBrandCSS() {
  const brand = readJSON('color-brand.json');
  const blocks = Object.entries(brand).map(([client, tokens]) => {
    const vars = flattenToVars(tokens, 'color');
    return `/* ${client} */\n[data-brand='${client}'] {\n${renderVars(vars)}\n}`;
  });
  writeFile(FOUNDATION, 'color-brand.css', HEADER + blocks.join('\n\n') + '\n');
}

function generateOpacityCSS() {
  const vars = flattenToVars(readJSON('opacity.json'), 'opacity');
  writeFile(FOUNDATION, 'opacity.css', HEADER + themeBlock(vars) + '\n');
}

function generateEffectsCSS() {
  const vars = flattenToVars(readJSON('effects.json'));
  const sections = [
    ['/* Shadows */',    filterByPrefix(vars, 'shadow')],
    ['/* Animations */', filterByPrefix(vars, 'animate')],
  ].filter(([, v]) => Object.keys(v).length > 0);

  const body = sections.map(([c, v]) => `  ${c}\n${renderVars(v)}`).join('\n\n');
  writeFile(FOUNDATION, 'effects.css', HEADER + `@theme {\n${body}\n}\n`);
}

function generateTypographyCSS() {
  const vars = flattenToVars(readJSON('typography.json'), 'font');
  const sections = [
    ['/* Font Family */',    filterByPrefix(vars, 'font-family')],
    ['/* Font Weight */',    filterByPrefix(vars, 'font-weight')],
    ['/* Font Size */',      filterByPrefix(vars, 'font-size')],
    ['/* Line Height */',    filterByPrefix(vars, 'font-lineHeight')],
    ['/* Letter Spacing */', filterByPrefix(vars, 'font-letterSpacing')],
  ].filter(([, v]) => Object.keys(v).length > 0);

  const body = sections.map(([c, v]) => `  ${c}\n${renderVars(v)}`).join('\n\n');
  writeFile(FOUNDATION, 'typography.css', HEADER + `@theme {\n${body}\n}\n`);
}

// ─── foundation/index.css  (공유 토큰 진입점 — 자동 갱신) ──
function generateFoundationIndex() {
  const shared = ['color.css', 'opacity.css', 'effects.css', 'typography.css'];
  const content = [
    HEADER,
    '/* 공유 토큰 진입점 — Tailwind 없이 CSS 변수만 필요할 때 import */',
    '/* dark.css / color-brand.css 는 조건부 사용이므로 별도 import */',
    '',
    shared.map(f => `@import './${f}';`).join('\n'),
    '',
  ].join('\n');
  writeFile(FOUNDATION, 'index.css', content);
}

// ─── web/base.css  (mw spacing + web typography) ──
function generateWebBaseCSS() {
  const spacing    = readJSON('spacing.json');
  const typoW      = readJSON('typography-w.json');

  const sizeVars   = flattenToVars(spacing.size, 'size');
  const mwVars     = flattenToVars(spacing.mw);
  const koVars     = flattenToVars(typoW.ko, 'w');

  const sections = [
    ['/* Sizes */',          sizeVars],
    ['/* Padding (mw) */',   filterByPrefix(mwVars, 'padding')],
    ['/* Spacing (mw) */',   filterByPrefix(mwVars, 'spacing')],
    ['/* Corner Radius */',  filterByPrefix(mwVars, 'cornerRadius')],
    ['/* Typography (w) */', koVars],
  ];

  let body = sections
    .filter(([, v]) => Object.keys(v).length > 0)
    .map(([c, v]) => `  ${c}\n${renderVars(v)}`)
    .join('\n\n');

  let content = HEADER + `@theme {\n${body}\n}\n`;

  // EN / JP 언어 오버라이드
  const langMap = { en: "html[lang='en']", jp: "html[lang='jp']" };
  for (const [lang, selector] of Object.entries(langMap)) {
    if (!typoW[lang]) continue;
    const diff = diffVars(koVars, flattenToVars(typoW[lang], 'w'));
    if (Object.keys(diff).length > 0) {
      content += `\n${selector} {\n${renderVars(diff)}\n}\n`;
    }
  }

  writeFile(WEB_OUT, 'base.css', content);
}

// ─── web/index.css  (최초 1회만 생성) ──────
function ensureWebIndex() {
  const dest = path.join(WEB_OUT, 'index.css');
  if (fs.existsSync(dest)) return;

  const content = `/* 폰트는 항상 최상위에서 import */
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css');
@import '@fontsource-variable/m-plus-2';

/* Tailwind */
@import 'tailwindcss';
@plugin "tailwindcss-animate";

/* 공유 토큰 */
@import '../foundation/index.css' layer(base);

/* 웹 플랫폼 토큰 */
@import './base.css' layer(base);

/* 다크 모드 (조건부) */
@import '../foundation/dark.css' layer(dark);

@layer base {
  html {
    font-family: var(--font-family-pretendard);
    font-size: 16px;
    user-select: none;
  }

  html[lang='ko'] {
    font-family: var(--font-family-pretendard);
  }

  html[lang='jp'] {
    font-family: var(--font-family-m-plus-2);
    font-weight: 1 999;
  }

  button:focus { outline: none; }

  .prevent-select {
    -webkit-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  input:focus {
    outline: none !important;
    box-shadow: none !important;
  }
}
`;
  writeFile(WEB_OUT, 'index.css', content);
}

// ─── vg/base.css  (vgk spacing + tablet typography) ──
function generateVGBaseCSS() {
  const spacing    = readJSON('spacing.json');
  const typoVG     = readJSON('typography-vg.json');

  const sizeVars   = flattenToVars(spacing.size, 'size');
  const vgkVars    = flattenToVars(spacing.vgk);
  const koVars     = flattenToVars(typoVG.ko, 't');

  const sections = [
    ['/* Sizes */',               sizeVars],
    ['/* Padding (vgk) */',       filterByPrefix(vgkVars, 'padding')],
    ['/* Spacing (vgk) */',       filterByPrefix(vgkVars, 'spacing')],
    ['/* Corner Radius (vgk) */', filterByPrefix(vgkVars, 'cornerRadius')],
    ['/* Typography (tablet) */', koVars],
  ];

  let body = sections
    .filter(([, v]) => Object.keys(v).length > 0)
    .map(([c, v]) => `  ${c}\n${renderVars(v)}`)
    .join('\n\n');

  let content = HEADER + `@theme {\n${body}\n}\n`;

  // EN / JP 언어 오버라이드
  const langMap = { en: "html[lang='en']", jp: "html[lang='jp']" };
  for (const [lang, selector] of Object.entries(langMap)) {
    if (!typoVG[lang]) continue;
    const diff = diffVars(koVars, flattenToVars(typoVG[lang], 't'));
    if (Object.keys(diff).length > 0) {
      content += `\n${selector} {\n${renderVars(diff)}\n}\n`;
    }
  }

  writeFile(VG_OUT, 'base.css', content);
}

// ─── vg/index.css  (최초 1회만 생성) ───────
function ensureVGIndex() {
  const dest = path.join(VG_OUT, 'index.css');
  if (fs.existsSync(dest)) return;

  const content = `/* 폰트는 항상 최상위에서 import */
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css');
@import '@fontsource-variable/m-plus-2';

/* Tailwind */
@import 'tailwindcss';
@plugin "tailwindcss-animate";

/* 공유 토큰 */
@import '../foundation/index.css' layer(base);

/* VGK 플랫폼 토큰 */
@import './base.css' layer(base);

/* 다크 모드 (조건부) */
@import '../foundation/dark.css' layer(dark);

@layer base {
  html {
    font-family: var(--font-family-pretendard);
    font-size: 16px;
    user-select: none;
  }

  html[lang='ko'] {
    font-family: var(--font-family-pretendard);
  }

  html[lang='jp'] {
    font-family: var(--font-family-m-plus-2);
    font-weight: 1 999;
  }

  button:focus { outline: none; }
}
`;
  writeFile(VG_OUT, 'index.css', content);
}

// ─── 실행 ─────────────────────────────────────
console.log('\n🔄 토큰 동기화 시작...\n');
try {
  console.log('[ foundation/ — 공유 토큰 ]');
  generateColorCSS();
  generateDarkCSS();
  generateColorBrandCSS();
  generateOpacityCSS();
  generateEffectsCSS();
  generateTypographyCSS();
  generateFoundationIndex();

  console.log('\n[ web/ — 웹 플랫폼 ]');
  generateWebBaseCSS();
  ensureWebIndex();

  console.log('\n[ vg/ — VGK 플랫폼 ]');
  generateVGBaseCSS();
  ensureVGIndex();

  console.log('\n✅ 동기화 완료\n');
} catch (err) {
  console.error('\n❌ 동기화 실패:', err.message);
  console.error(err.stack);
  process.exit(1);
}
