#!/usr/bin/env node

/**
 * JSON → CSS 토큰 동기화 스크립트
 *
 * JSON 파일을 수정한 뒤 `npm run sync`를 실행하면
 * root/styles/ 하위 CSS 파일이 자동 생성됩니다.
 *
 * 참조 표기법: {path.to.token} → var(--path-to-token)
 * 특수 키 "_": 상위 키만 CSS 변수명으로 사용 (예: spacing._ → --spacing)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FOUNDATION = path.join(ROOT, 'root', 'foundation');
const STYLES_OUT = path.join(ROOT, 'root', 'styles');

// 생성된 토큰 CSS 파일 목록 추적 (foundation/index.css 자동 갱신용)
const generatedTokenFiles = [];

// {path.to.token} → var(--path-to-token)
function resolveRefs(value) {
  if (typeof value !== 'string') return String(value);
  return value.replace(/\{([^}]+)\}/g, (_, tokenPath) => {
    return `var(--${tokenPath.replace(/\./g, '-')})`;
  });
}

// 중첩 객체를 { '--var-name': 'value' } 형태로 평탄화
function flattenToVars(obj, prefix = '') {
  const vars = {};
  for (const [key, value] of Object.entries(obj)) {
    const varName = key === '_' ? prefix : (prefix ? `${prefix}-${key}` : key);
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      Object.assign(vars, flattenToVars(value, varName));
    } else {
      vars[`--${varName}`] = resolveRefs(value);
    }
  }
  return vars;
}

function renderVars(vars, indent = '  ') {
  return Object.entries(vars)
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join('\n');
}

function readJSON(filename) {
  return JSON.parse(fs.readFileSync(path.join(FOUNDATION, filename), 'utf-8'));
}

function writeCSS(filename, content) {
  const fullPath = path.join(STYLES_OUT, filename);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content, 'utf-8');
  console.log(`  ✓ ${path.relative(ROOT, fullPath)}`);
  // index.css 제외한 토큰 CSS만 추적
  if (filename !== 'index.css') generatedTokenFiles.push(filename);
}

function filterByPrefix(vars, prefix) {
  return Object.fromEntries(
    Object.entries(vars).filter(([k]) => k.startsWith(`--${prefix}-`) || k === `--${prefix}`)
  );
}

// ─────────────────────────────────────────────
// color.css  (글로벌 컬러 + 라이트 시맨틱 컬러)
// ─────────────────────────────────────────────
function generateColorCSS() {
  const global = readJSON('color-global.json');
  const semantic = readJSON('color-semantic.json');

  const globalVars = flattenToVars(global, 'color');
  const lightVars  = flattenToVars(semantic.light, 'color');

  const content = [
    '/* Generated by scripts/sync-tokens.js — DO NOT EDIT DIRECTLY */',
    '@theme {',
    '  /* Global Colors */',
    renderVars(globalVars),
    '',
    '  /* Semantic Colors (Light) */',
    renderVars(lightVars),
    '}',
    '',
  ].join('\n');

  writeCSS('color.css', content);
}

// ─────────────────────────────────────────────
// dark.css  (다크 시맨틱 컬러)
// ─────────────────────────────────────────────
function generateDarkCSS() {
  const semantic = readJSON('color-semantic.json');
  const darkVars  = flattenToVars(semantic.dark, 'color');

  const content = [
    '/* Generated by scripts/sync-tokens.js — DO NOT EDIT DIRECTLY */',
    ':where(.dark) {',
    renderVars(darkVars),
    '}',
    '',
  ].join('\n');

  writeCSS('dark.css', content);
}

// ─────────────────────────────────────────────
// base.css  (spacing + typography + effects)
// ─────────────────────────────────────────────
function generateBaseCSS() {
  const spacing    = readJSON('spacing.json');
  const typography = readJSON('typography.json');
  const effects    = readJSON('effects.json');

  const spacingVars    = flattenToVars(spacing);
  const typographyVars = flattenToVars(typography);
  const effectsVars    = flattenToVars(effects);

  const sections = [
    ['/* Fonts */',         filterByPrefix(typographyVars, 'font')],
    ['/* Text Sizes */',    filterByPrefix(typographyVars, 'text-size')],
    ['/* Letter Spacing */',filterByPrefix(typographyVars, 'tracking')],
    ['/* Sizes */',         filterByPrefix(spacingVars, 'size')],
    ['/* Padding */',       filterByPrefix(spacingVars, 'padding')],
    ['/* Spacing */',       filterByPrefix(spacingVars, 'spacing')],
    ['/* Corner Radius */', filterByPrefix(spacingVars, 'radius')],
    ['/* Gap */',           filterByPrefix(spacingVars, 'gap')],
    ['/* Shadows */',       filterByPrefix(effectsVars, 'shadow')],
    ['/* Animations */',    filterByPrefix(effectsVars, 'animate')],
  ];

  const body = sections
    .filter(([, vars]) => Object.keys(vars).length > 0)
    .map(([comment, vars]) => `  ${comment}\n${renderVars(vars)}`)
    .join('\n\n');

  const content = [
    '/* Generated by scripts/sync-tokens.js — DO NOT EDIT DIRECTLY */',
    '@theme {',
    body,
    '}',
    '',
  ].join('\n');

  writeCSS('base.css', content);
}

// ─────────────────────────────────────────────
// root/foundation/index.css  (토큰 전용 진입점 — 자동 갱신)
// Tailwind 없이 CSS 변수만 사용하고 싶을 때 이 파일을 import
// 새 JSON 파일이 추가되면 자동으로 import 줄이 추가됨
// ─────────────────────────────────────────────
function generateFoundationIndex() {
  const imports = generatedTokenFiles
    .map(f => `@import '../styles/${f}';`)
    .join('\n');

  const content = [
    '/* Generated by scripts/sync-tokens.js — DO NOT EDIT DIRECTLY */',
    '/* 토큰 전용 진입점: Tailwind 없이 CSS 변수만 필요할 때 import */',
    '',
    imports,
    '',
  ].join('\n');

  const fullPath = path.join(FOUNDATION, 'index.css');
  fs.writeFileSync(fullPath, content, 'utf-8');
  console.log(`  ✓ ${path.relative(ROOT, fullPath)}`);
}

// ─────────────────────────────────────────────
// root/styles/index.css  (진입점 — 재생성 시 덮어쓰지 않음)
// ─────────────────────────────────────────────
function ensureIndexCSS() {
  const dest = path.join(STYLES_OUT, 'index.css');
  if (fs.existsSync(dest)) return;

  const content = `/* 폰트는 항상 최상위에서 import */
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css');
@import '@fontsource-variable/m-plus-2';

/* Web 에서 사용하는 Tailwind Token */
@import 'tailwindcss';
@plugin "tailwindcss-animate";

@import './base.css' layer(base);
@import './color.css' layer(colors);
@import './dark.css' layer(dark);

@layer base {
  html {
    font-family: var(--font-basic);
    font-size: 16px;
    user-select: none;
  }

  html[lang='ko'] {
    font-family: var(--font-sans-ko);
  }

  html[lang='jp'] {
    font-family: var(--font-sans-jp);
    font-weight: 1 999;
  }

  button:focus {
    outline: none;
  }

  .prevent-select {
    -webkit-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }
  input:focus {
    outline: none !important;
    box-shadow: none !important;
    -webkit-tap-highlight-color: transparent;
    -webkit-focus-ring-color: transparent;
  }
}

@layer utilities {
  .rounded-s {
    border-radius: var(--radius-s);
  }

  .rounded-l {
    border-radius: var(--radius-l);
  }
}
`;
  fs.writeFileSync(dest, content, 'utf-8');
  console.log(`  ✓ ${path.relative(ROOT, dest)} (최초 생성)`);
}

// ─────────────────────────────────────────────
// 실행
// ─────────────────────────────────────────────
console.log('\n🔄 토큰 동기화 시작...\n');
try {
  generateColorCSS();
  generateDarkCSS();
  generateBaseCSS();
  ensureIndexCSS();
  generateFoundationIndex();
  console.log('\n✅ 동기화 완료: root/styles/ + root/foundation/index.css\n');
} catch (err) {
  console.error('\n❌ 동기화 실패:', err.message);
  process.exit(1);
}
